version: "3"

services:
    postgres:

        image: postgres:latest
        container_name: db-postgres
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: gobarber
        volumes:
            - postgres-db-data:/data
        networks:
            - container-network
    mongo:
        image: mongo:latest
        container_name: db-mongo
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo-db-data:/data
        networks:
            - container-network
    api:
        build: .
        command: sh -c "./wait-for.sh postgres:5432 -- yarn typeorm migration:run && yarn dev"
        depends_on:
            - postgres
            - mongo
        container_name: node-js-backend
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - "3333:3333"

        networks:
            - container-network

volumes:
    postgres-db-data:
    mongo-db-data:

networks:
    container-network:
        driver: bridge
