version: "3"

services:
    database:
        image: postgres:latest
        container_name: db-postgres
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: gobarber
        volumes:
            - postgres-db-data:/data
        networks:
            - container-network
    api:
        build: .
        command: sh -c "./wait-for.sh database:5432 -- yarn typeorm migration:run && yarn dev"
        depends_on:
            - database
        container_name: node-js-backend
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - "3333:3333"

        networks:
            - container-network

volumes:
    postgres-db-data:

networks:
    container-network:
        driver: bridge
