version: "3"

services:
    database:
        image: postgres:latest
        container_name: db-postgress
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - postgres-db-data:/data
        networks:
            - container-network
    gobarber-api:
        depends_on:
            - database
        build: .
        command:
            - "cd gobarber-backend"
            - "yarn typeorm migration:run"
            - "yarn dev"

        container_name: gobarber-api
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - "3333:3333"

        networks:
            - container-network

volumes:
    postgres-db-data:

networks:
    container-network:
        driver: bridge
